# permissions for end users to edit postgresdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresdatabase-editor-role
rules:
- apiGroups:
  - database.kuberly.io
  resources:
  - postgresdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.kuberly.io
  resources:
  - postgresdatabases/status
  verbs:
  - get
