---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - database.kuberly.io
  resources:
  - valkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.kuberly.io
  resources:
  - valkeys/finalizers
  verbs:
  - update
- apiGroups:
  - database.kuberly.io
  resources:
  - valkeys/status
  verbs:
  - get
  - patch
  - update
