# permissions for end users to view valkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkey-viewer-role
rules:
- apiGroups:
  - database.kuberly.io
  resources:
  - valkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.kuberly.io
  resources:
  - valkeys/status
  verbs:
  - get
